### ISSUE TITLE
Сообщения от группы помечаются как подозрительные

### ISSUE THREAD

**Issue by eXpressionist** [TiraelSedai/ClubDoorman#12]
Админ чата приватный, все сообщения идут от имени группы .
```
Это подозрительное сообщение - например, картинка/видео/кружок/голосовуха без подписи от 'нового' юзера, или сообщение от канала. Сообщение НЕ удалено.
Юзер Group из чата <..>
```
Если не запускать с ключом DOORMAN_CHANNELS_AUTOBAN_DISABLE=1, то вовсе удаляет и пытается забанить :)

**Comment by TiraelSedai** [comment]
Кажется пофиксил, но нет возможности протестить, отпишись пожалуйста
@eXpressionist

**Comment by eXpressionist** [comment]
Похоже, помогло. Так просто было)
