### ISSUE TITLE
ARM?

### ISSUE THREAD

**Issue by seventhsite** [TiraelSedai/ClubDoorman#3]
Как можно это сбилдить под ARM?

**Comment by TiraelSedai** [comment]
`docker build .` в директории где лежит докерфайл должно работать (ну а поскольку оно должно работать то можно взять готовый контейнер с docker pull ghcr.io/tiraelsedai/clubdoorman:latest)
мака на арме у меня нет, проверить не могу, если есть какие-то конкретные ошибки, давайте рассмотрим

**Comment by seventhsite** [comment]
При попытке взять "как есть":

` ! doorman The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

и потом:

```
# docker compose logs -f
antispam  | exec /usr/bin/dotnet: exec format error
antispam  | exec /usr/bin/dotnet: exec format error
antispam  | exec /usr/bin/dotnet: exec format error
```


Да, успешно работает с 

`sudo docker build -t ghcr.io/tiraelsedai/clubdoorman:latest .`

Не думал, что компиляция производится прямо в том же образе, это же по-идее его сильно раздувает, нет? Не знаком с C#, но, возможно, стоит компиляцию производить где-то снаружи, а внутрь образа копировать только нужные файлы и минимизировать количество команд в Dockerfile.

**Comment by TiraelSedai** [comment]
@seventhsite это обычный [мультистейдж билд](https://docs.docker.com/build/building/multi-stage/), странно что ты с ним не сталкивался. мы берём имейдж сдк, билдим им, берём имейдж рантайма и перекладываем в него билд артефакты

как сделать мультиархитектурный имейдж я немного затрудняюсь, думал что "оно само", потому что и mcr.microsoft.com/dotnet/runtime мультиарч, и dotnet publish вызывается без указаний на архитектуру (если билдить только под линукс надо указать -r linux-x64)
